/*
 * Memory data — pure data, no "use client" directive.
 * Importable from both server and client components.
 * year field on work nodes enables chronological spiral layout.
 */

export const MEMORIES = [
  {
    id: "root",
    label: "nikolai onken",
    desc: "Coder, builder, musician. Lover of nature, humans, and the universe.",
    type: "root",
    connections: ["asymmetric", "cloud9", "uxebu", "warpmetrics", "coder"],
  },
  {
    id: "dojo",
    label: "Dojo Toolkit",
    desc: "Committer & community evangelist",
    url: "https://dojotoolkit.org",
    type: "work",
    year: 2008,
    connections: [],
  },
  {
    id: "uxebu",
    label: "uxebu",
    desc: "Co-founder — web & mobile development consultancy",
    url: "http://uxebu.com",
    type: "work",
    year: 2009,
    connections: ["bonsaijs"],
  },
  {
    id: "bonsaijs",
    label: "BonsaiJS",
    desc: "Open source HTML5 graphics library",
    type: "work",
    year: 2012,
    connections: ["dojo"],
  },
  {
    id: "cloud9",
    label: "Cloud9 IDE",
    desc: "Site lead — established the Amsterdam office. Acquired by AWS in 2016",
    url: "https://c9.io",
    type: "work",
    year: 2013,
    connections: ["aws"],
  },
  {
    id: "aws",
    label: "AWS",
    desc: "Site lead, Amsterdam (Cloud9)",
    url: "https://aws.amazon.com/cloud9/",
    type: "work",
    year: 2016,
    connections: [],
  },
  {
    id: "asymmetric",
    label: "Asymmetric",
    desc: "CTO — crypto-focused investment firm",
    url: "https://asymmetric.financial/",
    type: "work",
    year: 2018,
    connections: ["mintline", "dailydots", "nangu"],
  },
  {
    id: "nangu",
    label: "Nangu.eco",
    desc: "Co-founder",
    url: "https://nangu.eco/",
    type: "work",
    year: 2020,
    connections: ["baseline"],
  },
  {
    id: "baseline",
    label: "Baseline.dev",
    url: "https://baseline.dev/",
    type: "work",
    year: 2021,
    connections: ["saasmanual"],
  },
  {
    id: "saasmanual",
    label: "SaaS Manual",
    desc: "Learn how to build SaaS products from scratch",
    url: "https://saasmanual.com/",
    type: "work",
    year: 2021,
    connections: [],
  },
  {
    id: "mintline",
    label: "Mintline.ai",
    desc: "AI-powered financial reconciliation",
    url: "https://mintline.ai/",
    type: "work",
    year: 2023,
    connections: [],
  },
  {
    id: "dailydots",
    label: "DailyDots",
    url: "https://www.dailydots.com/",
    type: "work",
    year: 2023,
    connections: [],
  },
  {
    id: "warpmetrics",
    label: "WarpMetrics",
    desc: "AI-powered coding agents",
    url: "https://warpmetrics.com/",
    type: "work",
    year: 2024,
    connections: ["coder"],
  },
  {
    id: "coder",
    label: "Coder",
    type: "identity",
    connections: ["builder"],
  },
  {
    id: "builder",
    label: "Builder",
    type: "identity",
    connections: ["musician"],
  },
  {
    id: "musician",
    label: "Musician",
    type: "identity",
    connections: ["nature", "humans"],
  },
  {
    id: "nature",
    label: "Nature",
    type: "identity",
    connections: ["universe", "humans"],
  },
  {
    id: "humans",
    label: "Humans",
    type: "identity",
    connections: [],
  },
  {
    id: "universe",
    label: "Universe",
    type: "identity",
    connections: [],
  },
];
